apiVersion: app/v1
kind: Deployment
metadata:
  name: demo-cicd-docker-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-cicd-docker-kubernetes
  template:
    metadata:
      labels:
        app: demo-cicd-docker-kubernetes
    spec:
      containers:
        - name: springboot
          image: lexuanphi/demo-cicd-docker-kubernetes
          ports:
            - containerPort: 8080
          env:
            - name: POST
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-cicd-docker-kubernetes
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
      app: demo-cicd-docker-kubernetes